### ISSUE TITLE
Accessing original component

### ISSUE THREAD

**Issue by kof** [jsstyles/react-jss#15]
When we wrap a component with jss, how do we call methods of original component?

**Comment by kof** [comment]
Seems like we can do it via `this.refs.something.wrapped` where  wrapped points to the original component .... however not sure if this is nice and also what happens if we have more than one layer.

**Comment by kof** [comment]
Also the bad thing is that an external component needs to have the knowledge if a component has been wrapped and how much times.

**Comment by gaearon** [comment]
Accessing component's methods is very rarely a good idea. Component's API is its props.

There are cases when it makes sense (e.g. router transition hooks) but it's better to keep styling to leaf components, and keep those “smart” components (that may have transition hooks) without their own styles.

This is not just a problem for React JSS, it's the same problem for every other wrapping library. Which indicates “let's just expose it” is rarely a solution because every lib will expose the wrapped component under a different name.

The real solution is to:

* not call component's instance methods from the outside and use props instead (good design)
* when needed to add static methods, add them to the decorated class instead

See an example in this issue: https://github.com/acdlite/flummox/issues/173#issuecomment-100552563

```js
function statics(a) {
  return b => Object.assign(b, a)
}

// ...

import React from 'react';
import useSheet from 'react-jss';
import statics from './statics';

// I made my own decorator for adding stuff to the wrapped component
@statics({
  willTransitionTo(transition) {
    transition.abort();
  }
})
@useSheet(styles)
export default class SomeRoute{
  render() {
    return <div>{this.props.someProp}</div>
  }
}
```

Could also write this without decorators:

```js
import React from 'react';
import useSheet from 'react-jss';

class SomeRoute{
  render() {
    return <div>{this.props.someProp}</div>
  }
}

SomeRoute = useSheet(SomeRoute, styles);

Object.assign(SomeRoute, {
  willTransitionTo(transition) {
    transition.abort();
  }
});

export default SomeRoute;
```

**Comment by kof** [comment]
What do you think about passing `props.componentDidMount` and call it from the proper component with component instance as param?

**Comment by gaearon** [comment]
Why do that? I don't understand the use case.

**Comment by kof** [comment]
The use case is to get the component instance and get its dom node.

**Comment by gaearon** [comment]
I don't understand why you'd need the actual component instance.
Instead, you can create your own wrapper:

```js
class SomethingThatNeedsToDoSomeWorkOnDOM {
  componentDidMount() {
    findDOMNode(this).doStuff();
  }

  render() {
    return <SomethingThatUsesReactJSS />
  }
}
```

**Comment by gaearon** [comment]
This also works with refs:

```js
class SomethingThatNeedsToDoSomeWorkOnDOM extends Component {
  componentDidMount() {
    findDOMNode(this.refs.lol).doStuff();
  }

  render() {
    return <div><SomethingThatUsesReactJSS ref='lol' /></div>
  }
}
```

**Comment by kof** [comment]
this ref will be JSS component, not the inner component ...

**Comment by gaearon** [comment]
What is your use case for accessing the instance?

You wrote above:

>The use case is to get the component instance and get its dom node.

You _will_ get the right DOM node this way.

What else do you need the instance for?

**Comment by kof** [comment]
Oh right, for the case of finding the right DOM node it should work, however acceessing components methods is still sometimes required ...

**Comment by gaearon** [comment]
React's `findDOMNode()` doesn't care if you pass something that's just a wrapper. Because React JSS [just renders its component as only child](https://github.com/jsstyles/react-jss/blob/master/src/index.js#L64), their DOM nodes will always match. There is no different between `findDOMNode(actualInstance)` and `findDOMNode(instanceWrappedByReactJSS)`, so to say.

> acceessing components methods is still sometimes required ...

For what? I wrote a ton of React code and never needed that. Everything is better expressed as props.

**Comment by kof** [comment]
let me see if I can rewrite the logic without accessing component ...

**Comment by gaearon** [comment]
I'm not *strictly* opposed to adding something like `getDecoratedInstance()`. But it's usually more harm than good because then somebody adds another wrapper and some code dependent on it breaks. On the other hand, even side effects are often more conveniently expressed as prop changes + `componentWillReceiveProps` hook.

**Comment by kof** [comment]
We need something that def works with any wrappers, we can't expect them all to implement getDecoratedInstance ...

**Comment by kof** [comment]
Lets take this example:

https://github.com/joshwnj/react-visibility-sensor/blob/master/visibility-sensor.js#L72

If we pass active: false and don't let the component call `.check` automatically (for performance reasons when there are lots of rendered sensors).

We want to make the check when required imperatively. How would you do that without to access a components method?

**Comment by gaearon** [comment]
We could use a similar API to React 0.13's callback refs.


```js
class VisibilitySensor {
  componentDidMount() {
    if (this.props.scheduleCheck) {
      this.props.scheduleCheck(this.check)
    } else {
      // setup timeout
    } 
  }

  componentWillUnmount() {
    if (this.props.scheduleCheck) {
      this.props.scheduleCheck(null)
    } else {
      // teardown timeout
    }
  }

  ...
}


class OtherComponent {
  componentDidUpdate() {
    if (someCondition) {
      this.checkSensor();
    }
  }

  render() {
    return (
      <VisibilitySensor
        scheduleCheck={check => this.checkSensor = check} />
    );
  }
}
```

**Comment by gaearon** [comment]
For comparison, React 0.13 callback refs (also imperative API):

```js
render() {
  return <Image ref={instance => this.imageRef = instance} />
}
```

**Comment by skevy** [comment]
Just saw @gaearon's tweet about this post.

Wanted to chime in and say that I've used this API in some apps I've built to get around the exact problem described in this issue. @gaearon is right - you almost never have to do this. But in the times you do (I needed to give some inner component a callback for when Packery was done laying stuff out)...and you have components that are wrapped with multiple decorators...it works great. It's clean (well, as clean as you can get when you're doing imperative stuff in a declarative domain) and makes it so lib authors don't have to add the `getDecoratedInstance()` type stuff to their HoC's.

**Comment by kof** [comment]
ref like callback is exactly what I ment by 
> What do you think about passing props.componentDidMount and call it from the proper component with component instance as param?

Passing componentDidMount via params and call it from any inner component. There is just one potential issue with this approach - if there is more than 1 wrapper components which expect props.componentDidMount and call it you get your callback more than once with different components)

**Comment by gaearon** [comment]
This is why I didn't suggest something “generic” like `componentDidMount`. It would look really weird together with “normal” `componentDidMount`. Instead, I suggest passing very specific hooks inside and solving this in particular components (in this case, it is up to `<VisibilitySensor>` to provide something like `scheduleCheck` in its public API). I don't think we should solve this in React JSS (or any other wrapper library).

**Comment by kof** [comment]
I think everything is clear here, closing it, thank you @gaearon !

**Comment by kof** [comment]
Actually its a brilliant idea to have a separate wrapper component if it has to b accessed imperatively. This way we separate public api from internal one. Its even nice for maintanance.

**Comment by Kagami** [comment]
Requirement to pass callback via props in order to save component's API method in caller instance each time is a **huge** boilerplate. I'm using this communication pattern a lot and now I'll probably abandon `react-jss` because of that.

>Accessing component's methods is very rarely a good idea. Component's API is its props.

What made you say that? Communication via component methods mentioned in official documentation [here](https://facebook.github.io/react/tips/expose-component-functions.html). There is no single mention it's deprecated or bad practice or something.

**Comment by kof** [comment]
We will release a react integration without a HOC, no dates though. There are already some prototypes for e.g.  https://github.com/nathanmarks/jss-theme-reactor by @nathanmarks 
As a side note: if you are using such a big amount of of methods that it becomes a huge boilerplate, you are def. doing something wrong ... in my experience it happens rarely.

**Comment by Kagami** [comment]
>We will release a react integration without a HOC

Great news.

>if you are using such a big amount of methods that it becomes a huge boilerplate, you are def. doing something wrong

Well, maybe, I don't have that much experience in React. Consider this simple example:

```
<div>
  <Toolbar>
    <Button onClick={this.refs.c1.action} />
    <Button onClick={this.refs.c2.action} />
  </Toolbar>
  <SubComponent1 ref="c1" />
  <SubComponent2 ref="c2" />
</div>
```

I have main component with buttons and subcomponents which provide some functionality (e.g. text editor, video player, etc). How would you interact with them without method calls? Events? Too clumsy IMO.

**Comment by kof** [comment]
> How would you interact with them without method calls?

This is pretty much offtopic here, pure react is using callbacks, also there are other alternatives.

**Comment by Kagami** [comment]
>pure react is using callbacks

Official documentation doesn't imply that.

>This is pretty much offtopic here

I just demonstrate in which cases method calls might be useful. Therefore without accessing component's functions directly you need to switch to alternate communication patterns. So far only [callback backpropogation](https://github.com/cssinjs/react-jss/issues/15#issuecomment-113151979) was proposed which results in boilerplate when you have a lot of methods. I don't get why discussing issues caused by component's architecture is offtopic. Do you know some better places for that?

**Comment by kof** [comment]
Because it is a topic "how to work with react in a declarative way" without overusing imperative methods. You will need to be precise about your specific code.  Can't recommend a specific tracker, but it should be about reacts architecture. Most probably start googling, the topic is as old as react itself.
