### ISSUE TITLE
react-transform-hmr support

### ISSUE THREAD

**Issue by godcore** [jsstyles/react-jss#29]
Does react-jss support [react-transform-hmr](https://github.com/gaearon/react-transform-hmr)? I'm trying to make them work together but still no luck. hot-update file is loaded and it contains updated style, but seems that stylesheet is not replaced after.
I asked this question in [react-transform-hmr project](https://github.com/gaearon/react-transform-hmr/issues/35) but haven't got any answers. 
Thnx in advance.

**Comment by kof** [comment]
can't tell you, need to try out.

**Comment by gaearon** [comment]
Not currently. Please see https://github.com/gaearon/babel-plugin-react-transform/issues/26 for the explanation. When/if Babel plugin learns to wrap exports, it will work. For now, you can either use [React Hot Loader](https://github.com/gaearon/react-hot-loader) instead of the Babel plugin, or [use vanilla HMR API (but in this case you’ll lose component state on hot reloads)](https://github.com/reactjs/redux/pull/1455).

**Comment by gaearon** [comment]
Works with [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61):

![](https://s3.amazonaws.com/f.cl.ly/items/431L2L0r1b3q0O0p0q11/Screen%20Recording%202016-04-18%20at%2015.16.gif?v=52fde2ac)

**Comment by kof** [comment]
nice, need to check it out.

**Comment by kof** [comment]
we should ad an exampe to the https://github.com/jsstyles/examples repository of a react-jss setup with hot reloader 3
